
export const STATES = {
  INITIAL: "INITIAL",
  FINISHED: "FINISHED",
  GETTING_FULL_NAME: "GETTING_FULL_NAME",
  GETTING_RECRUITER_NAME: "GETTING_RECRUITER_NAME",
  GETTING_JOB_POSITION: "GETTING_JOB_POSITION",
  QUESTION_1: "QUESTION_1",
  QUESTION_2: "QUESTION_2",
  QUESTION_3: "QUESTION_3",
  QUESTION_4: "QUESTION_4",
  QUESTION_5: "QUESTION_5"
};
